services:
  backend:
    build: .
    container_name: ciclothe_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    networks:
      - ciclothe_network
    depends_on:
      - db
      - minio

  db:
    image: mysql:8.0
    container_name: ciclothe_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ciclothe_network

  minio:
    image: minio/minio
    container_name: ciclothe_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ciclothe_network

networks:
  ciclothe_network:

volumes:
  db_data:
  minio_data:
